name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Compile library and testing
      run: make lib build/testing
        
    - name: Compile docs
      uses: mattnotmitt/doxygen-action@v1.3.0
    
    - name: Compile PDF docs
      uses: xu-cheng/texlive-action/full@v1
      with:
        run: |
            apk add make
            make pdf
            mv docs/docs.pdf docs/html
            cp docs/html/docs.pdf docs.pdf
      
    - name: Publish docs to github pages
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        folder: docs/html
        branch: gh-pages
    
    - name: Create release zip file
      run: zip release.zip *.h testing.c build/myLibrary.lib docs.pdf
        
    - name: Publish build
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.ACCESS_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Development build"
        files: release.zip
