name: Doxygen compilation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    # This workflow contains a single job called "build"
    steps:
      - uses: mattnotmitt/doxygen-action@v1.3.0
      - name: doxygen
        run: doxygen
